version: '3.8'
services:
  tomcat1:
    build: ./tomcat1
    container_name: tomcat1
    expose:
      - 8080
    #ports:
    #  - "8081:8080"
  tomcat2:
    build: ./tomcat2
    container_name: tomcat2
    expose:
      - 8080
    #ports: 
     # - "8082:8080"
  nginx:
    build: ./nginx
    container_name: nginx_tomcat
    ports:
      - "8080:8080"
    depends_on:
      - tomcat1
      - tomcat2